### ISSUE TITLE
Analysis interpretation

### ISSUE THREAD

**Issue by MickWest1** [jbpease/dfoil#2]
Dear James,

I posted this in the other thread but because it was closed I was not sure you would get notified so opened this new one.

Thank you for your help. I managed to get it working now I think. The pdf is a little messy but I think the analyze output should be easier to interpret. I have added my output for the introgression calls. I am guessing the first column is the order of introgression? e.g. from my data 14 1 means 1 window supported introgression from taxon 1 into taxon 4? If this is the case, what do none mean and na?

Introgression Calls:
none 8511
14 1
23 6
na 999
41 3
123 73
124 70
32 1

Thank you for any help.

**Comment by jbpease** [comment]
Hi Mick,

The "none" means "no introgression"
"na" means "not enough ABBA or BABA sites"
"14" means introgression from P1-to-P4 (and so forth)
"123" means ancestral introgression between P1+2 and P3 (this is directionless).

**Comment by MickWest1** [comment]
Hi James

Ok great. Thank you very much for clarifying

**Comment by jbpease** [comment]
Hi Mick, 

Sincere apologies for the delay!  I would say that if you are seeing a fair amont of 123 and 124, with some 14 and 23 coming in more irregularly, then a conservative interpretation would be gene flow is occuring, but the specific players or directionality are not clear.  The number of significant windows going down as your window size drops is not surprising, since you are losing number of biallelic sites (i.e. signal).  Happy to chat more about this, and again I apologize this slipped through the cracks.  

James

**Comment by MickWest1** [comment]
No problem, thank you for replying anyway. I did some additional analyses and it seems like the most likely reasoning is that the ancestors of 12 and 34 mixed quite early on after their divergence and there was probably very little to no subsequent admixture after the 34 lineages had split. 

Thanks,
Mick

**Comment by jbpease** [comment]
That makes sense.  That's definitely a limitation of these types of data.  The ability to detect depends on the amount of divergence between the species relative to the introgression time.  Glad it's working.
